- hosts: all
  gather_facts: yes

  vars:
    server_name: "{{ inventory_hostname }}"

  tasks:
    - name: Install cowsay package
      ansible.builtin.package:
        name: cowsay
        state: present

    - name: Run cowsay command
      command: cowsay "This is server {{ server_name }}!"
      register: cowsay_result

    - name: Create index.html fileg
      ansible.builtin.template:
        src: ../templates/index.html.j2
        dest: /usr/share/nginx/html/index.html

    - name: Display cowsay result
      ansible.builtin.debug:
        msg: "{{ cowsay_result.stdout }}"

    - name: Check cowsay result in HTML
      ansible.builtin.lineinfile:
        path: /usr/share/nginx/html/index.html
        line: "<pre><code>{{ cowsay_result.stdout }}</code></pre>"
        insertafter: "<h2>THIS IS SERVER {{ server_name }}!</h2>"