- name: install git
  hosts: all
  become: yes
  tasks:
    - name: update cache pakage
      ansible.builtin.apt:
        update_cache: yes
      tag: update

    - name: install pakage git
      ansible.builtin.apt:
        name: git
        state: present
      tags: install

    - name: install pakage make
      ansible.builtin.apt:
        name: make
        state: present
      tags: install
    
    - name: install pakage nodejs
      ansible.builtin.apt:
        name: nodejs
        state: present 
      tags:
        - install

    - name: install pakage git
      ansible.builtin.apt:
        name: git
        state: present
      tags: unistall

    - name: install pakage make
      ansible.builtin.apt:
        name: make
        state: present
      tags: unistall
    
    - name: install pakage nodejs
      ansible.builtin.apt:
        name: nodejs
        state: present 
      tags:
        - unistall