- name: install git
  hosts: all
  become: yes
  tasks:
    - name: update cache pakage
      ansible.builtin.apt:
        update_cache: yes

    - name: install pakage git
      ansible.builtin.apt:
        name: git
        state: present