    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes

    - name: update nginx config
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        force: yes
      loop:
        - { src: 'files/nginx.conf', dest: '/etc/nginx/nginx.conf' }
        - { src: 'files/index.html', dest: '/usr/share/nginx/html/index.html' }
      notify:
        - restart nginx
      become: yes
